name: Tests
on: 
    push: 
        branches: [master]
jobs: 
    build: 
        runs-on: ubuntu-latest
        steps: 
            -   name: Copy my github code
                uses: actions/checkout@v3
            -   name: Set up node version 18
                uses: actions/setup-node@v3
                with:
                    node-version: "18.x"
            -   name: "Install dependencies"
                run: npm install
            -   name: Run Test
                run: npm run test